### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Jason0919** [gitblit/gitblit#1002]
I set server.requireClientCertificates = true on the server.

The client to get a certificate to set up the browser to open the web site, and the use of mysigit can also clone the project, but Egit Eclipse can not clone the project although I set up the false http.sslVerify

How can I do that, Egit can access the project

**Comment by gitblit** [comment]
As far as I know Egit does not support cloning using client X509 certificates.

**Comment by Jason0919** [comment]
Egit want cloning project, you must set up the server. The requireClientCertificates = false?

**Comment by gitblit** [comment]
`server.requireClientCertifiicates=true` forces Gitblit to reject any incoming http/https connections that do not offer an X509 certificate created by the Gitblit Authority.  While Gitblit does support X509 certificate authentication, support for this mechanism in Git clients is spotty.  **EGit does not support X509 certificate authentication** so I would advised leaving this setting `false` if you intend to use EGit with Gitblit.

If you are trying to clone from EGit using a self-signed SSL certificate on your server (e.g. you are running Gitblit GO which generates a certificate on startup), then you must set `http.sslVerify=false` on your clients either for this repo clone OR globally.  This setting instructs git to ignore the fact that your Gitblit's SSL certificate is not signed by a known/registered/trusted Certificate Authority (CA).  Some would advise not setting that globally because it disables protection against man-in-the-middle attacks.  However, that choice is up to you and certainly if you are running both server and client within your own LAN then this is a non-issue IMO.

**Comment by Jason0919** [comment]
Thank you very much for your answer, it is very useful for me.

I do not want to let the outside world to access, you can set the gitblit certificate into a domain certificate, is it?
