### ISSUE TITLE
Wrong summary information about branch creation

### ISSUE THREAD

**Issue by monkiki** [gitblit/gitblit#1080]
Hi,

The problem I've seen is that the information in the summary page which refers to a branch creation is showing not the user who created the branch but the user who created the master branch.

See this user history:
- User A creates the repository, so the master branch is created by him.
- User B creates a branch, but in the summary this branch appears as created by user A.

Thanks.

**Comment by jameyg42** [comment]
i'm not sure specifically what area of the summary page you're referring to, but i don't believe there is such a thing as "branch owner/creator" (there's no metadata anywhere that contains such information).  Perhaps you're simply misinterpreting something on the summary page (or perhaps a screenshot)?

**Comment by fzs** [comment]
What Jamey said. There is no "branch creator". If in your example you created a branch on master and pushed without a new commit on it, it will show the same as for the master branch. Because they both point to the same commit and the branch section shows the author and commit message of the commit a branch is pointing to.
