### ISSUE TITLE
Domain - how to attach?

### ISSUE THREAD

**Issue by BitSums** [gitblit/gitblit#1148]
As instead of ip address to set domain?
For example: git.domain.com

**Comment by BitSums** [comment]
Good support......

**Comment by gitblit** [comment]
Good description of problem. Please elaborate.

**Comment by BitSums** [comment]
At the moment I enter the web interface ip.
How do I change the ip domain?
![iijq494wwualkqfaxdf49q](https://cloud.githubusercontent.com/assets/20419550/20483187/c893d80e-b001-11e6-99aa-13d175d1619f.jpg)

**Comment by gitblit** [comment]
If you are hosting Gitblit within a LAN, then I don't know the correct answer... but most modern Linux distros do properly register a hostname with your router so that you can use local hostname resolution within your LAN.

If you are hosting Gitblit on a publicly accessible ip address, then you would need to purchase a domain (e.g. `domain.com`) from a registrar and setup a DNS `A` record for that domain to point to your Gitblit instance (e.g. `git.domain.com` => a.b.c.d).

**Comment by BitSums** [comment]
No, i have domain...
How do I replace them ip address? Open a web server?

**Comment by BitSums** [comment]
How can I use a domain name now? Domain meets all requirements

**Comment by gitblit** [comment]
Sorry. I don't completely understand what you are asking.

Assuming you have assigned the IP address of your Gitblit server to your domain name then internet DNS will take over and you should be able to use the domain name in your browser.

Once you have that working then you can set web.canonicalUrl and your clone instructions and email notifications will have the proper urls.

Either way I think you should seek assistance somewhere else since we're having trouble communicating and, from what I can tell, this is not really a Gitblit issue.
