### ISSUE TITLE
How to translate gitblit?

### ISSUE THREAD

**Issue by martinrotter** [gitblit/gitblit#1180]

**Comment by fzs** [comment]
A non-issue? =)


In any case, there are language files for different languages:
````
gitblit $ find . -name *_pl*
./src/main/java/com/gitblit/wicket/pages/EmptyRepositoryPage_pl.html
./src/main/java/com/gitblit/wicket/GitBlitWebApp_pl.properties
./src/main/java/welcome_pl.mkd
./src/main/java/login_pl.mkd
````

To add support for a new language you would create new versions of these files with the langue code at the end of the file name, e.g. `GitBlitWebApp_cs.properties`, with the new translation.

**Comment by martinrotter** [comment]
Yea, that is nice, but those PL files contains Polish strings? I want to translate from English. Are there prepared English files to be translated?

**Comment by fzs** [comment]
Of course, you start from the files without a country code extension, so:
````
src/main/java/com/gitblit/wicket/pages/EmptyRepositoryPage.html
src/main/java/com/gitblit/wicket/GitBlitWebApp.properties
src/main/java/welcome.mkd
src/main/java/login.mkd
````

**Comment by martinrotter** [comment]
Oh, I have must missed those files. Thanks.

**Comment by gitblit** [comment]
One thing to note about resource bundles (`.properties`) in Java - the encoding is required to be 8859-1 - which is dumb since the rest of Java has been Unicode friendly from day 1, but that's the way it is.  Wicket has some support for decoding UTF-8 `.properties` files automatically, but we do not rely on that.

We often need to use `native2ascii` from a Linux machine (maybe Mac too, not sure) to convert from UTF-8 to non Latin-1 characters encoded as `\uNNNN`.  That's just an FYI.
