### ISSUE TITLE
Bump min java version to 1.8

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#1218]
We should bump the min java version to 1.8 in the next release so we can bump jetty version and other deps and other deps which requires java 1.8+.

**Comment by fzs** [comment]
I vote against it. I wouldn't want to force Java 8 as a requirement on users of Gitblit. Not just so that it can use the latest versions of whatever dependencies it has without reason.
Gitblit is a server application running on stable systems, not a game or desktop app running on the latest, greatest PC. Wide spread Linux server distributions like Debian Jessie or Ubuntu 14.04, for example still come with Java 7.

While there is merit in keeping up-to-date with dependencies, there should still be a good reason why an update is done, if the system currently is working. So updating all dependencies just because, and thereby stepping up the Java requirement, is not a good idea, I think.

**Comment by pingunaut** [comment]
I vote for java 8 as a minimal version. Java 9 is already released and Java 7 reached its public end of life long time ago. I just ran an OWASP-dependeny check against GitBlit source and the result was... improvable. From a security point of view, it would be good to have the chance to update to patched versions of dependencies. Stability could be ensured by raising test coverage... and maybe beta/milestone releases?

**Comment by ghmer** [comment]
Given the time between releases, I vote for Java11. It is the actual LTS. Java 8 would have been an option 3 years ago.

**Comment by TomaszSzt** [comment]
Voting for JDK 8 also. It is harder and harder to set-up build environment to use jdk7. Recently You must even keep two versions of ANT as only up to 1.9 allows to use pre 8 JDK what can be a real mess up.

**Comment by andrm** [comment]
Voting for Java 11.

**Comment by flaix** [comment]
From Gitblit version 1.10.0 on the minimum Java version is Java 8.
