### ISSUE TITLE
Copy repository url to clipboard with JS

### ISSUE THREAD

**Issue by mystygage** [gitblit/gitblit#1241]
Most browser today support `document.execCommand('copy')` so it would be nice to have this option instead of the 1-step flash or 3-step JS solution

**Comment by TDesjardins** [comment]
Another solution is to simply use https://clipboardjs.com/

**Comment by flaix** [comment]
Ideally, you would create a pull request.
Alternatively, you could attach a patch as a file to this issue.
If you need help with either of the two, let mw know.
The solution I would implement would work like the one used earlier with the Flash button, i.e. click the copy button to copy the URL. Which is not unlike Github does it.

**Comment by piradix** [comment]
ok for copy button. ...

**Comment by piradix** [comment]
To integrate a copy button (remove flash button et prompt button) do this (it is a js solution) : 
- download clipboard.js from https://clipboardjs.com/ : https://codeload.github.com/zenorocha/clipboard.js/zip/refs/heads/master
- copy from this archive the file clipboard.js-master/dist/clipboard.min.js into src/main/resources/clipboard.js/clipboard.min.js
- edit file src/main/java/com/gitblit/wicket/pages/BasePage.html line 56 after `<script type="text/javascript" src="gitblit/js/collapsible-table.js"></script>`  
copy the code 
```
                <script type="text/javascript" src="clipboard/js/clipboard.min.js"></script>
		<script type="text/javascript"> 
		  var clipboardJsList = [
			  new ClipboardJS(".clipboardjs",{ target: function(trigger) { 
				  var items = trigger.parentElement.getElementsByClassName("clipboardjs-text");
				  if( items!=null && items.length>0 ) 
					  return items[0];
				  return trigger; }  
			  }),			  
		  ]; 		  
		</script>
```
- save the file
- edit file "/src/main/java/com/gitblit/wicket/panels/RepositoryUrlPanel.html"
- find (line 18) replace all `<div class="repositoryUrl "> ... </div>` by 
 ```
 <div class="repositoryUrl ">
   <span class="clipboardjs-text"><span wicket:id="primaryUrl">[repository primary url]</span></span>
   <span class="fa fa-copy clipboardjs" ></span>
 </div>
 ```
- save the file
- try it (see image) ....
![Screenshot 2022-11-19 at 23-29-24 depot-test git - Gitblit](https://user-images.githubusercontent.com/64977993/202874031-efdc4509-2747-49d4-9342-062b31abf64e.png)
![Screenshot 2022-11-19 at 23-29-24 depot-test git - Gitblit](https://user-images.githubusercontent.com/64977993/202874071-a263c961-ae48-4a42-8ec7-8142d6e585a1.png)

**Comment by flaix** [comment]
I was just spending some time, looking into clipboardjs and the ways it can be integrated. Is there any specific reason why you chose the function an to work with a parent element?

**Comment by flaix** [comment]
I have started the implementation in pull request #1438. Feel invited to review it.
Do you have a good idea how to display a tooltip, like when you click the copy button on Github's repository page? It will give you a "Copied" tooltip for a few seconds.

**Comment by piradix** [comment]
> Is there a specific reason why you chose the an function to work with a parent element?

Yes, I don't know the java framework used and it removes the "span" declaration when it affects the text. So, I wrote a button where the click is used by the clipboardjs library.  The problem is then to recover the text (without knowing the Id, because it is the java framework that puts it). So I use the parent as search point followed by the "clipboard-text" class. It's easier and can be adapted to many situations.
In general, I try to decorate the back-office from UX/UI (front office)

PS : usually, I use Java back offices as data service, and the user interface, I write it in html/js/css with the framework Aurelia.io (kind of Angular framework, VueJS, but simpler) => MVC.
Here, if I understood correctly, the framework mixes controller+vue,  like React does in JS.

**Comment by piradix** [comment]
I will look at







From:   "Florian Zschocke" ***@***.***>
To:     "gitblit/gitblit" ***@***.***>
Cc:     "piradix" ***@***.***>, "Comment" 
***@***.***>
Date:   20/11/2022 19:13
Subject:        Re: [gitblit/gitblit] Copy repository url to clipboard 
with JS (#1241)



I have started the implementation in pull request #1438. Feel invited to 
review it.
Do you have a good idea how to display a tooltip, like when you click the 
copy button on Github's repository page? It will give you a "Copied" 
tooltip for a few seconds.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: 
***@***.***>

**Comment by piradix** [comment]
>Do you have a good idea how to display a tooltip, like when you click the copy button on Github's repository page? It will give you a "Copied" tooltip for a few seconds.

I'll look for

**Comment by flaix** [comment]
I added some code for a tool tip.

**Comment by piradix** [comment]
>I added some code for a tool tip.

Can I see it ? (branch ... tag ... )

**Comment by flaix** [comment]
@piradix, if you didn't find any issues with it I'm going to merge the pull request.

**Comment by piradix** [comment]
I see the icon "copy", but click don't work (no event are under it).
In fact, it doesn't download the 2 new js file "clipboard.min.js" and "gitblit-ctcbtn.js".
These files exist in "/Gitblit/src/main/resources/clipboard/"
I suppose is due to component use line 56 of BasPage.html  `<wicket:container wicket:id="bottomScripts"></wicket:container>`


And if you want to put the icon to the right of line and not after the text, write the icon in first of line, then in it style add "float: right". => all copy icon'll be align to right line. It is more beautiful for sub menu of git, Smartgit/hg ...
Example : 
`<span class="hidden-phone hidden-tablet" style="float: right;"><img class="ctcbtn" src="../clippy.png" data-clipboard-target="#id15" title="copier dans le presse-papier">/span>`

Otherwise the line size will not be good (=>css hack). See image ...
![Screenshot 2022-11-24 at 12-04-26 test git - Gitblit](https://user-images.githubusercontent.com/64977993/203769000-307453c4-977f-47cc-b543-01184357f149.png)

**Comment by flaix** [comment]
Which browser do you test with an how do you run Gitblit?
I tested with Firefox and had Gitblit running from the IDE and with "moxie run" under macOS as well as building a GO version and installing it on a Linux machine and testing from localhost as well as through a reverse proxy. The copy worked in all cases.

**Comment by flaix** [comment]
I tried with Eclipse as IDE on macOS, Firefox 107. I do see the .js files getting downloaded in the dev tools network tab, and copying as well as the tooltip work for me. Same with Safari.

**Comment by piradix** [comment]
It run getBottomScriptContainer()
But it don't run method addBottomScript()

**Comment by piradix** [comment]
I find the problem 
- if depot is empty (no file), you get my problem (see image): buttons are show but disabled.
- else all are right

![Screenshot 2022-11-24 at 19-42-08 test4 git - Gitblit](https://user-images.githubusercontent.com/64977993/203849418-00dfbb2c-a304-48d1-bdcf-e2db57244c7d.png)

**Comment by flaix** [comment]
Ah, excellent! Thank you!

**Comment by flaix** [comment]
There seems to be no french translation for the empty repository page. If you like, feel free to contibute one.

**Comment by piradix** [comment]
Where is the I18n properties file to translate or other files ?

**Comment by flaix** [comment]
You find the english file under `src/main/java/com/gitblit/wicket/pages/EmptyRepositoryPage.html` and would create a new `src/main/java/com/gitblit/wicket/pages/EmptyRepositoryPage_fr.html` file.

**Comment by piradix** [comment]
The French version, see zip file
[EmptyRepositoryPage_fr.zip](https://github.com/gitblit/gitblit/files/10147127/EmptyRepositoryPage_fr.zip)

**Comment by piradix** [comment]
The French version, see zip file
[EmptyRepositoryPage_fr.zip](https://github.com/gitblit/gitblit/files/10147158/EmptyRepositoryPage_fr.zip)
