### ISSUE TITLE
using own crt for ssl

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#394]
Originally reported on Google Code with ID 98

```
What steps will reproduce the problem?
1. type "keytool -import -alias hostname -file /path/to/cert.crt -storepass 123456"
2. go into gitblit.properties and change the server.storepassword to 123456
3. try to connect, and in chrome I instantly get a "Error 107 (net::ERR_SSL_PROTOCOL_ERROR):
SSL protocol error."

No other browsers can connect as well. Seems to have worked fine before I tried to
add my own keyfile, but really, this shoudn't be an issue.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
0.9.3

Please provide any additional information below.

```

Reported by `kelly.elton@skylabsonline.com` on 2012-05-17 19:06:56

**Comment by shadowfoxish** [comment]
Just wanted to leave a comment here since I was facing similar issues using a legitimate wildcard certificate to secure my GitBlit installation (1.8.0) with https. I think the biggest hurdles were generating the jks certificate file from the pfx file, ensuring the store password was the same and set in all the places (like the installservice.cmd file), and that the ```server.certificateAlias``` was set to something actually returned by ```keytool -list -v -keystore keystore.jks```. The alias wasn't a hostname for me, it was actually a {GUID}.

**Comment by shadowfoxish** [comment]
Additional info, as I had to update certs when they expired and have some additional observations to share. When you install the PFX in the Windows cert manager and allow for export of the private key, you have the option to re-export it later and "Include all certificates in the certification path if possible". Make sure you do this. I used Portecle to create the new JKS file and imported my newly exported PFX which included the whole cert chain. Portecle can show you the certs embedded in the file and if you only have the one, then its no good. In my case, I had 3 certs. This was my flux certpacitor. I found I really didn't need to do anything with the serverTrustStore.jks file.
