### ISSUE TITLE
error: RPC failed; result=22, HTTP code = 413

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#461]
Originally reported on Google Code with ID 165

```
What steps will reproduce the problem?
1. Stage a large number of file like 3000
2. git push
3.

What is the expected output? What do you see instead?
Expected output is "Push successful", Instead i see

Counting objects: 2474, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2407/2407), done.
Writing objects: 100% (2469/2469), 8.14 MiB | 4.92 MiB/s, done.
Total 2469 (delta 316), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 413
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

What version of the product are you using? On what operating system?
GitBlit Express 1.1.0

Please provide any additional information below.


```

Reported by `haseeb.yousaf@pentaloop.com` on 2012-11-16 10:30:05

**Comment by milosmns** [comment]
I'll write this comment on as many places as possible, I've just lost an hour trying to figure out what is happening. Even though it might not be related to the stuff you discussed, I'm pretty sure that people stumble upon this link as much as I do, so hopefully some of them will get the solution.

The problem:
- Your push data is too big for the server. You can't send large files over HTTP by default (you could, but it requires server changes). And, of course, you don't have access to the server.

The solution: 
- Switch to SSH protocol.

Switching to SSH
----------------
1. Go to your `$projectRoot/.git/` and open the `config` file
2. Inside of your `config` file you should add the marked line
```
[remote "origin"]
	url = http://git.domain.com/repo/repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = git@git.domain.com:repo/repo.git # <-- THIS LINE
```
Note that `#` is the comment delimiter and you don't have to write it.
This forces the push URL to use the SSH protocol.
3. Save but don't close

Still having issues? Yeah, that's because you need a proper SSH certificate (i.e. either generate a new public/private key pair or use the existing ones). That's easy to find on Google, look for "Generate SSH key".

Configuring Git to use SSH
--------------------------

Now you have the two keys (private & public). Here is what I did to get them correctly configured with my Git client.

1. Start the SSH agent. Preconditions: (1) Git must be in your path, or `cd` into the `Git/bin` directory; (2) You must be able to use the `eval` command - either use Unix (Linux/Mac) or download Git Bash for Windows and go from there.
To start the SSH agent, run this:
``` eval $(ssh-agent -s) ```
You will get something like this as a response: 
``` Agent pid 1996 ```

2. Add your SSH key so that Git can use it later:
``` ssh-add your_key_name_here ```
The output for that will be something like
```
Enter passphrase for your_key_name_here:
Identity added: your_key_name_here (your_key_name_here)
```
Note that this was not the `.pub` (public) key.

3. Now go to your repository's website/config (i.e. GitHub, GitLab, BitBucket...) and search through profile and repository settings - you want to find a button that allows you to upload your other (public) SSH key. If your two keys don't match, then the push will fail. If that happens, you messed up the SSH generation somehow.

4. Okay! Last step, finally.
``` git push ```
And your output should be something like this (push does not fail):
```
Counting objects: 99, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (94/94), done.
Writing objects: 100% (99/99), 6.74 MiB | 233.00 KiB/s, done.
Total 99 (delta 33), reused 0 (delta 0)
To git.domain.com:repo/repo.git
   f1b618b..43f0f23  master -> master
```

Hope this helps.

Oh! One more thing. Remember when I told you not to close the `.git/config` file? Yeah, you might want to comment out the `pushurl` parameter now - my IDE was unable to use SSH so I reverted to HTTP. When I'm pushing large files, I quickly go to this page and run through the manual again... ...
