### ISSUE TITLE
XSS request parameter filtering magles parameters by inserting HTML character entities.

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#822]
Originally reported on Google Code with ID 526

```
What steps will reproduce the problem?
1. Check in a file name "à.txt" in a git repository.
2. View that commit in GitBlit.
3. Try to view the file, or a diff with the file.

What is the expected output? What do you see instead?

Expected: The file is shown (view, raw links), or a diff is shown (commitdiff, for
instance).

Actual: GitBlit complains that it cannot find the file &amp;agrave;.txt.

What version of the product are you using? On what operating system?

GitBlit 1.6.2 as part of a Gerrit plugin.

Please provide any additional information below.

The problem is in JSoupXssFilter.clean(): the final call to html() introduces these
entities. That's correct when you want to insert the result into HTML, but if that
happens on request parameters, subsequent processing is broken because file paths have
been mangled.
```

Reported by `tw201207` on 2014-11-04 23:09:09

**Comment by flaix** [comment]
Quoting from the OWASP page:

> Input validation or data sanitization can also be performed to help prevent Server XSS, but it’s much more difficult to get correct than context-sensitive output encoding.

**Comment by flaix** [comment]
I tried the steps to reproduce with Gitblit 1.9.1. I was not able to reproduce this. The file named `à.txt` could be opened, also in raw view. A diff was also possible without problems.
I also tried this with a folder with non-ASCII characters in the name, also no problems encountered.

Seems like this has been fixed by some change in the past.
