### ISSUE TITLE
Encrypt password of mail settings

### ISSUE THREAD

**Issue by josivan** [gitblit/gitblit#987]
How can I encrypt the password of mail settings?

I would like something similar of approach used in hash funciont in h2 database or OBF: used in jetty.

Regards

**Comment by gitblit** [comment]
Currently there is no mechanism to support encryption/decryption of settings.  If the SMTP password was encrypted then we'd need to store decryption keys so that the clear-text password could be retrieved and sent to the SMTP server.

This is a different use-case than the authentication use-case for which OBF works nicely.  The mechanisms you cite are one-way hashes.  The server would use them to store a hashed password and then compare it to future hashed candidate passwords.

In the mail case, the SMTP server wants the clear password, not a one-way hashed representation.

**Comment by josivan** [comment]
Thanks for answering James (@gitblit).

Regards

**Comment by josivan** [comment]
I believe that #1074 solve this issue/suggestion.
